// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreRopa.Data;

#nullable disable

namespace StoreRopa.Migrations
{
    [DbContext(typeof(StoreDBContext))]
    [Migration("20230801014809_Clientes")]
    partial class Clientes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StoreRopa.Models.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(1)
                        .HasComment("Identificador de la tabla");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("EsActivo")
                        .HasColumnType("bit")
                        .HasColumnOrder(5)
                        .HasComment("Indica si el registro se encuentra activo y se puede usar");

                    b.Property<bool>("EsEliminado")
                        .HasColumnType("bit")
                        .HasColumnOrder(6)
                        .HasComment("Indica si el registro a sido eliminado(eliminado logico)");

                    b.Property<long>("PersonaId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2)
                        .HasComment("Persona");

                    b.Property<decimal>("Saldo")
                        .IsUnicode(false)
                        .HasColumnType("DECIMAL(14,2)")
                        .HasColumnOrder(3)
                        .HasComment("Saldo del cliente");

                    b.Property<int>("TipoVenta")
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnOrder(4)
                        .HasComment("Tipo de venta que se le hará al cliente");

                    b.HasKey("Id")
                        .HasName("PK_cliente");

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("StoreRopa.Models.Persona", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(1)
                        .HasComment("Identificador de la tabla");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ApMaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(4)
                        .HasComment("Apellido materno de la persona");

                    b.Property<string>("ApPaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(3)
                        .HasComment("Apellido paterno de la persona");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnOrder(7)
                        .HasComment("Ciudad donde vive la persona");

                    b.Property<int?>("Cp")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnOrder(11)
                        .HasComment("Codigo postal de su ubicación de la persona");

                    b.Property<string>("Curp")
                        .IsRequired()
                        .HasMaxLength(18)
                        .IsUnicode(false)
                        .HasColumnType("varchar(18)")
                        .HasColumnOrder(5)
                        .HasComment("Curp (unica) de la persona");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)")
                        .HasColumnOrder(9)
                        .HasComment("Direccion especifica de la persona");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("bit")
                        .HasColumnOrder(101)
                        .HasComment("Indica si el registro se encuentra activo y se puede usar");

                    b.Property<bool>("EsEliminado")
                        .HasColumnType("bit")
                        .HasColumnOrder(102)
                        .HasComment("Indica si el registro a sido eliminado(eliminado logico)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime")
                        .HasColumnOrder(103)
                        .HasComment("Fecha en que se crea el registro");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnOrder(105)
                        .HasComment("Ultima fecha que se actualiza el registro");

                    b.Property<DateTime?>("FechaNacimiento")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("datetime")
                        .HasColumnOrder(6)
                        .HasComment("fecha de nacimiento de la persona");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnOrder(2)
                        .HasComment("Nombre de la persona");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnOrder(10)
                        .HasComment("Numero donde se situa su ubicación de la persona");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnOrder(8)
                        .HasComment("Pais donde vive la persona");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnOrder(12)
                        .HasComment("Numero telefonico de la persona");

                    b.Property<string>("UsuarioAlta")
                        .HasColumnType("varchar(200)")
                        .HasColumnOrder(104)
                        .HasComment("Usuario que crea el registro");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("varchar(20)")
                        .HasColumnOrder(106)
                        .HasComment("Ultimo usuario que actualiza el registro");

                    b.HasKey("Id")
                        .HasName("PK_persona");

                    b.ToTable("Persona", (string)null);
                });

            modelBuilder.Entity("StoreRopa.Models.Cliente", b =>
                {
                    b.HasOne("StoreRopa.Models.Persona", "Persona")
                        .WithOne("Cliente")
                        .HasForeignKey("StoreRopa.Models.Cliente", "PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Persona_Cliente");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("StoreRopa.Models.Persona", b =>
                {
                    b.Navigation("Cliente")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
