// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreRopa.Data;

#nullable disable

namespace StoreRopa.Migrations
{
    [DbContext(typeof(StoreDBContext))]
    [Migration("20240907004422_InitMigration")]
    partial class InitMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StoreRopa.Models.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(1)
                        .HasComment("Identificador de la tabla");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("EsActivo")
                        .HasColumnType("bit")
                        .HasColumnOrder(101)
                        .HasComment("Indica si el registro se encuentra activo y se puede usar");

                    b.Property<bool>("EsEliminado")
                        .HasColumnType("bit")
                        .HasColumnOrder(102)
                        .HasComment("Indica si el registro a sido eliminado(eliminado logico)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime")
                        .HasColumnOrder(103)
                        .HasComment("Fecha en que se crea el registro");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnOrder(105)
                        .HasComment("Ultima fecha que se actualiza el registro");

                    b.Property<long>("PersonaId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2)
                        .HasComment("Persona");

                    b.Property<decimal>("Saldo")
                        .IsUnicode(false)
                        .HasColumnType("DECIMAL(14,2)")
                        .HasColumnOrder(3)
                        .HasComment("Saldo del cliente");

                    b.Property<int?>("TipoVenta")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnOrder(4)
                        .HasComment("Tipo de venta que se le hará al cliente");

                    b.Property<string>("UsuarioAlta")
                        .HasColumnType("varchar(200)")
                        .HasColumnOrder(104)
                        .HasComment("Usuario que crea el registro");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("varchar(20)")
                        .HasColumnOrder(106)
                        .HasComment("Ultimo usuario que actualiza el registro");

                    b.HasKey("Id")
                        .HasName("PK_cliente");

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("StoreRopa.Models.Creditos", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(1)
                        .HasComment("Identificador de la tabla");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DetalleVentaId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2)
                        .HasComment("Detalle de la Venta");

                    b.Property<bool>("EsActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnOrder(101)
                        .HasDefaultValueSql("1")
                        .HasComment("Indica si el registro se encuentra activo y se puede usar");

                    b.Property<bool>("EsEliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnOrder(102)
                        .HasDefaultValueSql("0")
                        .HasComment("Indica si el registro a sido eliminado(eliminado logico)");

                    b.Property<DateTime>("FechaAlta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnOrder(103)
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Fecha en que se crea el registro");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnOrder(105)
                        .HasComment("Ultima fecha que se actualiza el registro");

                    b.Property<decimal>("PagoPendiente")
                        .IsUnicode(false)
                        .HasColumnType("DECIMAL(14,2)")
                        .HasColumnOrder(4)
                        .HasComment("Saldo pendiente de pago del articulo");

                    b.Property<decimal>("PrecioArticulo")
                        .IsUnicode(false)
                        .HasColumnType("DECIMAL(14,2)")
                        .HasColumnOrder(3)
                        .HasComment("Precio del articulo");

                    b.Property<string>("UsuarioAlta")
                        .HasColumnType("varchar(50)")
                        .HasColumnOrder(104)
                        .HasComment("Usuario que crea el registro");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("varchar(50)")
                        .HasColumnOrder(106)
                        .HasComment("Ultimo usuario que actualiza el registro");

                    b.HasKey("Id")
                        .HasName("PK_Creditos");

                    b.HasIndex("DetalleVentaId");

                    b.ToTable("Creditos", (string)null);
                });

            modelBuilder.Entity("StoreRopa.Models.DetalleVentas", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(1)
                        .HasComment("Identificador de la tabla");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(5)
                        .HasComment("Color del articulo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnOrder(3)
                        .HasComment("Descripción del articulo");

                    b.Property<decimal>("Descuento")
                        .IsUnicode(false)
                        .HasColumnType("DECIMAL(14,2)")
                        .HasColumnOrder(8)
                        .HasComment("Descuento que se aplica al articulo");

                    b.Property<bool>("EsActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnOrder(101)
                        .HasDefaultValueSql("1")
                        .HasComment("Indica si el registro se encuentra activo y se puede usar");

                    b.Property<bool>("EsEliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnOrder(102)
                        .HasDefaultValueSql("0")
                        .HasComment("Indica si el registro a sido eliminado(eliminado logico)");

                    b.Property<DateTime>("FechaAlta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnOrder(103)
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Fecha en que se crea el registro");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnOrder(105)
                        .HasComment("Ultima fecha que se actualiza el registro");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnOrder(6)
                        .HasComment("Modelo del articulo");

                    b.Property<decimal>("PrecioArticulo")
                        .IsUnicode(false)
                        .HasColumnType("DECIMAL(14,2)")
                        .HasColumnOrder(7)
                        .HasComment("Precio del articulo");

                    b.Property<decimal>("PrecioVenta")
                        .IsUnicode(false)
                        .HasColumnType("DECIMAL(14,2)")
                        .HasColumnOrder(9)
                        .HasComment("Precio real de venta");

                    b.Property<string>("Talla")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnOrder(4)
                        .HasComment("Talla del articulo");

                    b.Property<string>("UsuarioAlta")
                        .HasColumnType("varchar(50)")
                        .HasColumnOrder(104)
                        .HasComment("Usuario que crea el registro");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("varchar(50)")
                        .HasColumnOrder(106)
                        .HasComment("Ultimo usuario que actualiza el registro");

                    b.Property<long>("VentaId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2)
                        .HasComment("Venta");

                    b.HasKey("Id")
                        .HasName("PK_detalleVenta");

                    b.HasIndex("VentaId");

                    b.ToTable("DetalleVentas", (string)null);
                });

            modelBuilder.Entity("StoreRopa.Models.Empleados", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(1)
                        .HasComment("Identificador de la tabla");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("EsActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnOrder(101)
                        .HasDefaultValueSql("1")
                        .HasComment("Indica si el registro se encuentra activo y se puede usar");

                    b.Property<bool>("EsEliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnOrder(102)
                        .HasDefaultValueSql("0")
                        .HasComment("Indica si el registro a sido eliminado(eliminado logico)");

                    b.Property<DateTime>("FechaAlta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnOrder(103)
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Fecha en que se crea el registro");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnOrder(105)
                        .HasComment("Ultima fecha que se actualiza el registro");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(5)
                        .HasComment("Clave de acceso");

                    b.Property<long>("PersonaId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2)
                        .HasComment("Persona");

                    b.Property<long>("RolId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(3);

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnOrder(4)
                        .HasComment("Nombre del usuario");

                    b.Property<string>("UsuarioAlta")
                        .HasColumnType("varchar(50)")
                        .HasColumnOrder(104)
                        .HasComment("Usuario que crea el registro");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("varchar(50)")
                        .HasColumnOrder(106)
                        .HasComment("Ultimo usuario que actualiza el registro");

                    b.HasKey("Id")
                        .HasName("PK_empleado");

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Empleado", (string)null);
                });

            modelBuilder.Entity("StoreRopa.Models.Persona", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(1)
                        .HasComment("Identificador de la tabla");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ApMaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(4)
                        .HasComment("Apellido materno de la persona");

                    b.Property<string>("ApPaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(3)
                        .HasComment("Apellido paterno de la persona");

                    b.Property<int?>("Cp")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnOrder(11)
                        .HasComment("Codigo postal de su ubicación de la persona");

                    b.Property<string>("Curp")
                        .IsRequired()
                        .HasMaxLength(18)
                        .IsUnicode(false)
                        .HasColumnType("varchar(18)")
                        .HasColumnOrder(5)
                        .HasComment("Curp (unica) de la persona");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)")
                        .HasColumnOrder(9)
                        .HasComment("Direccion especifica de la persona");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("bit")
                        .HasColumnOrder(101)
                        .HasComment("Indica si el registro se encuentra activo y se puede usar");

                    b.Property<bool>("EsEliminado")
                        .HasColumnType("bit")
                        .HasColumnOrder(102)
                        .HasComment("Indica si el registro a sido eliminado(eliminado logico)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnOrder(8)
                        .HasComment("Estado donde vive la persona");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime")
                        .HasColumnOrder(103)
                        .HasComment("Fecha en que se crea el registro");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnOrder(105)
                        .HasComment("Ultima fecha que se actualiza el registro");

                    b.Property<DateTime?>("FechaNacimiento")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("datetime")
                        .HasColumnOrder(6)
                        .HasComment("fecha de nacimiento de la persona");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnOrder(7)
                        .HasComment("Municipio donde vive la persona");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnOrder(2)
                        .HasComment("Nombre de la persona");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnOrder(10)
                        .HasComment("Numero donde se situa su ubicación de la persona");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnOrder(12)
                        .HasComment("Numero telefonico de la persona");

                    b.Property<string>("UsuarioAlta")
                        .HasColumnType("varchar(200)")
                        .HasColumnOrder(104)
                        .HasComment("Usuario que crea el registro");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("varchar(20)")
                        .HasColumnOrder(106)
                        .HasComment("Ultimo usuario que actualiza el registro");

                    b.HasKey("Id")
                        .HasName("PK_persona");

                    b.ToTable("Persona", (string)null);
                });

            modelBuilder.Entity("StoreRopa.Models.Roles", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(1)
                        .HasComment("Identificador de la tabla");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(3)
                        .HasComment("Descripción de las funciones del rol");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("bit")
                        .HasColumnOrder(101)
                        .HasComment("Indica si el registro se encuentra activo y se puede usar");

                    b.Property<bool>("EsEliminado")
                        .HasColumnType("bit")
                        .HasColumnOrder(102)
                        .HasComment("Indica si el registro a sido eliminado(eliminado logico)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime")
                        .HasColumnOrder(103)
                        .HasComment("Fecha en que se crea el registro");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnOrder(105)
                        .HasComment("Ultima fecha que se actualiza el registro");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnOrder(2)
                        .HasComment("Nombre del rol");

                    b.Property<string>("UsuarioAlta")
                        .HasColumnType("varchar(200)")
                        .HasColumnOrder(104)
                        .HasComment("Usuario que crea el registro");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("varchar(20)")
                        .HasColumnOrder(106)
                        .HasComment("Ultimo usuario que actualiza el registro");

                    b.HasKey("Id")
                        .HasName("PK_roles");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("StoreRopa.Models.Ventas", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(1)
                        .HasComment("Identificador de la tabla");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AbonoVenta")
                        .IsUnicode(false)
                        .HasColumnType("DECIMAL(14,2)")
                        .HasColumnOrder(5)
                        .HasComment("Dinero abonado a la venta");

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2)
                        .HasComment("Cliente");

                    b.Property<long>("EmpleadoId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(3)
                        .HasComment("Empleado");

                    b.Property<bool>("EsActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnOrder(101)
                        .HasDefaultValueSql("1")
                        .HasComment("Indica si el registro se encuentra activo y se puede usar");

                    b.Property<bool>("EsEliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnOrder(102)
                        .HasDefaultValueSql("0")
                        .HasComment("Indica si el registro a sido eliminado(eliminado logico)");

                    b.Property<bool>("EsVentaCredito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnOrder(7)
                        .HasDefaultValueSql("0")
                        .HasComment("Indica si la venta es a crédito");

                    b.Property<DateTime>("FechaAlta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnOrder(103)
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Fecha en que se crea el registro");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnOrder(105)
                        .HasComment("Ultima fecha que se actualiza el registro");

                    b.Property<decimal>("ImporteVenta")
                        .IsUnicode(false)
                        .HasColumnType("DECIMAL(14,2)")
                        .HasColumnOrder(4)
                        .HasComment("Importe total de la venta");

                    b.Property<decimal>("PendientePago")
                        .IsUnicode(false)
                        .HasColumnType("DECIMAL(14,2)")
                        .HasColumnOrder(6)
                        .HasComment("Saldo pendiente por pagar");

                    b.Property<string>("UsuarioAlta")
                        .HasColumnType("varchar(50)")
                        .HasColumnOrder(104)
                        .HasComment("Usuario que crea el registro");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("varchar(50)")
                        .HasColumnOrder(106)
                        .HasComment("Ultimo usuario que actualiza el registro");

                    b.HasKey("Id")
                        .HasName("PK_venta");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Ventas", (string)null);
                });

            modelBuilder.Entity("StoreRopa.Models.Cliente", b =>
                {
                    b.HasOne("StoreRopa.Models.Persona", "Persona")
                        .WithOne("Cliente")
                        .HasForeignKey("StoreRopa.Models.Cliente", "PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Persona_Cliente");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("StoreRopa.Models.Creditos", b =>
                {
                    b.HasOne("StoreRopa.Models.DetalleVentas", "DetalleVenta")
                        .WithMany("Creditos")
                        .HasForeignKey("DetalleVentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Credito_Venta");

                    b.Navigation("DetalleVenta");
                });

            modelBuilder.Entity("StoreRopa.Models.DetalleVentas", b =>
                {
                    b.HasOne("StoreRopa.Models.Ventas", "Venta")
                        .WithMany("DetalleVentas")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Venta_Detalle");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("StoreRopa.Models.Empleados", b =>
                {
                    b.HasOne("StoreRopa.Models.Persona", "Persona")
                        .WithOne("Empleado")
                        .HasForeignKey("StoreRopa.Models.Empleados", "PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Persona_Empleado");

                    b.HasOne("StoreRopa.Models.Roles", "Rol")
                        .WithMany("Empleados")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Rol_Empleado");

                    b.Navigation("Persona");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("StoreRopa.Models.Ventas", b =>
                {
                    b.HasOne("StoreRopa.Models.Cliente", "Cliente")
                        .WithMany("Ventas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Venta_Cliente");

                    b.HasOne("StoreRopa.Models.Empleados", "Empleado")
                        .WithMany("Ventas")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Venta_Empleado");

                    b.Navigation("Cliente");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("StoreRopa.Models.Cliente", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("StoreRopa.Models.DetalleVentas", b =>
                {
                    b.Navigation("Creditos");
                });

            modelBuilder.Entity("StoreRopa.Models.Empleados", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("StoreRopa.Models.Persona", b =>
                {
                    b.Navigation("Cliente")
                        .IsRequired();

                    b.Navigation("Empleado")
                        .IsRequired();
                });

            modelBuilder.Entity("StoreRopa.Models.Roles", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("StoreRopa.Models.Ventas", b =>
                {
                    b.Navigation("DetalleVentas");
                });
#pragma warning restore 612, 618
        }
    }
}
